import type {
  AgentSpec,
  AgentTeamDraft,
  ApprovalRequest,
  AuditEvent,
  OrganizationIntegration,
  ProgramFile,
  PublicationRecord,
  Run,
} from "@agent-marketplace/contracts";

export const overviewStats = [
  { label: "Live agents", value: 5, hint: "3 production, 2 staging" },
  { label: "Pending approvals", value: 4, hint: "External writes waiting" },
  { label: "Connected integrations", value: 6, hint: "Org-wide installs" },
  { label: "Runs today", value: 28, hint: "Read-only and approval flows" },
];

export const draftPreview: AgentTeamDraft = {
  id: "draft_demo",
  organizationId: "org_demo",
  workspaceId: "workspace_demo",
  title: "Revenue Recovery Team",
  brief:
    "We need a team that monitors inbound sales email, drafts next-step responses, updates CRM opportunities, and flags deals needing human approval before money-moving or customer-visible changes.",
  status: "generated",
  clarifications: [
    "Confirm which CRM is authoritative for pipeline stages.",
  ],
  generatedAgents: [
    {
      id: "draft_agent_pipeline",
      roleName: "Pipeline Operator",
      mission: "Keep the revenue pipeline current and escalate risky changes.",
      responsibilities: [
        "Review inbound deal updates.",
        "Prepare CRM and outbound response actions.",
      ],
      allowedTools: ["crm.contacts.read", "crm.tasks.write", "gmail.send"],
      knowledgeSources: ["workspace brief", "HubSpot install", "run history"],
      triggerModes: ["manual", "integration_event"],
      approvalPolicy: "required",
      successMetrics: ["Time to first follow-up", "CRM hygiene"],
      constraints: ["Require approval before outbound updates."],
    },
    {
      id: "draft_agent_support",
      roleName: "Customer Support Agent",
      mission: "Summarize support threads and prepare customer-ready drafts.",
      responsibilities: ["Read email threads.", "Draft responses and hand off."],
      allowedTools: ["gmail.read", "gmail.send", "slack.post"],
      knowledgeSources: ["workspace brief", "Gmail install"],
      triggerModes: ["manual", "integration_event"],
      approvalPolicy: "required",
      successMetrics: ["Queue response time", "Draft acceptance rate"],
      constraints: ["Do not send without approval."],
    },
  ],
  createdByUserId: "user_demo",
  updatedByUserId: "user_demo",
  createdAt: "2026-03-23T09:00:00.000Z",
  updatedAt: "2026-03-23T09:10:00.000Z",
};

export const agents: AgentSpec[] = [
  {
    id: "agent_pipeline",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    displayName: "Pipeline Operator",
    mission: "Keep CRM and outbound comms aligned to real pipeline state.",
    responsibilities: ["Watch inbound updates", "Prepare CRM mutations", "Stage follow-up drafts"],
    allowedTools: ["crm.contacts.read", "crm.tasks.write", "gmail.send"],
    knowledgeSources: ["HubSpot", "workspace brief", "past approvals"],
    triggerModes: ["manual", "integration_event"],
    approvalPolicy: "required",
    successMetrics: ["Pipeline freshness", "Follow-up time"],
    constraints: ["External writes need approval"],
    status: "active",
    currentVersionId: "agent_version_pipeline",
    createdAt: "2026-03-23T08:00:00.000Z",
    updatedAt: "2026-03-23T08:15:00.000Z",
  },
  {
    id: "agent_support",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    displayName: "Customer Support Agent",
    mission: "Reduce inbox drag by preparing accurate support drafts.",
    responsibilities: ["Read threads", "Summarize context", "Prepare responses"],
    allowedTools: ["gmail.read", "gmail.send", "slack.post"],
    knowledgeSources: ["Gmail", "Slack", "workspace brief"],
    triggerModes: ["manual", "integration_event"],
    approvalPolicy: "required",
    successMetrics: ["Draft reuse rate", "Escalation quality"],
    constraints: ["Never send without approval"],
    status: "active",
    currentVersionId: "agent_version_support",
    createdAt: "2026-03-22T18:00:00.000Z",
    updatedAt: "2026-03-23T07:00:00.000Z",
  },
];

export const integrations: OrganizationIntegration[] = [
  {
    id: "int_google",
    organizationId: "org_demo",
    providerKey: "google-workspace",
    displayName: "Go-to-market Google Workspace",
    status: "connected",
    authType: "oauth",
    scopes: ["gmail.read", "gmail.send", "calendar.read"],
    metadata: { domain: "example.com" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-20T10:00:00.000Z",
    updatedAt: "2026-03-22T10:00:00.000Z",
    lastValidatedAt: "2026-03-23T08:45:00.000Z",
  },
  {
    id: "int_hubspot",
    organizationId: "org_demo",
    providerKey: "hubspot",
    displayName: "Primary Revenue HubSpot",
    status: "connected",
    authType: "oauth",
    scopes: ["crm.contacts.read", "crm.tasks.write"],
    metadata: { portalId: "1234567" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-18T10:00:00.000Z",
    updatedAt: "2026-03-23T07:45:00.000Z",
    lastValidatedAt: "2026-03-23T08:30:00.000Z",
  },
  {
    id: "int_slack",
    organizationId: "org_demo",
    providerKey: "slack",
    displayName: "Ops Slack",
    status: "pending",
    authType: "oauth",
    scopes: ["slack.post"],
    metadata: { workspace: "ops" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:55:00.000Z",
    updatedAt: "2026-03-23T08:55:00.000Z",
    lastValidatedAt: null,
  },
  {
    id: "int_base",
    organizationId: "org_demo",
    providerKey: "base",
    displayName: "Base Publisher",
    status: "connected",
    authType: "wallet",
    scopes: ["base.publish_program", "base.register_manifest"],
    metadata: { chainId: 8453 },
    createdByUserId: "user_demo",
    createdAt: "2026-03-21T08:10:00.000Z",
    updatedAt: "2026-03-23T08:00:00.000Z",
    lastValidatedAt: "2026-03-23T08:00:00.000Z",
  },
  {
    id: "int_arweave",
    organizationId: "org_demo",
    providerKey: "arweave",
    displayName: "Arweave Publisher",
    status: "connected",
    authType: "wallet",
    scopes: ["arweave.upload_program", "arweave.pin_manifest"],
    metadata: { gateway: "https://arweave.net" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-21T08:20:00.000Z",
    updatedAt: "2026-03-23T08:05:00.000Z",
    lastValidatedAt: "2026-03-23T08:05:00.000Z",
  },
];

export const programFiles: ProgramFile[] = [
  {
    id: "program_file_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_pipeline",
    name: "pipeline-operator.manifest.json",
    description: "Publishable manifest for the Pipeline Operator runtime and grants.",
    sourceType: "json",
    content: '{\n  "name": "Pipeline Operator",\n  "version": 1,\n  "tools": ["crm.contacts.read", "crm.tasks.write", "gmail.send"]\n}',
    tags: ["manifest", "pipeline", "base", "arweave"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:40:00.000Z",
    updatedAt: "2026-03-23T08:40:00.000Z",
  },
  {
    id: "program_file_2",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_support",
    name: "support-agent.ts",
    description: "Typed program entrypoint for the support agent workflow.",
    sourceType: "typescript",
    content: 'export const supportProgram = { role: "Customer Support Agent", approvalPolicy: "required" };\n',
    tags: ["runtime", "support", "typescript"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:42:00.000Z",
    updatedAt: "2026-03-23T08:42:00.000Z",
  },
];

export const publicationRecords: PublicationRecord[] = [
  {
    id: "publication_base_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    programFileId: "program_file_1",
    target: "base",
    status: "published",
    organizationIntegrationId: "int_base",
    summary: "Published the pipeline manifest to Base.",
    transactionId: "base_pipeline_manifest_v1",
    gatewayUrl: "https://basescan.org/address/pipeline-operator-manifest-json",
    metadata: {
      chainId: 8453,
      tags: ["manifest", "pipeline"],
    },
    orchestration: {
      engine: "temporal",
      workflowId: "publication-publication_base_1",
      workflowRunId: "temporal-run-base-1",
      workflowType: "programPublicationWorkflow",
      taskQueue: "agent-marketplace-publications",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:50:00.000Z",
    updatedAt: "2026-03-23T08:51:00.000Z",
  },
  {
    id: "publication_arweave_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    programFileId: "program_file_1",
    target: "arweave",
    status: "published",
    organizationIntegrationId: "int_arweave",
    summary: "Pinned the same manifest to Arweave for immutable retrieval.",
    transactionId: "ar_pipeline_manifest_v1",
    gatewayUrl: "https://arweave.net/pipeline-operator-manifest-json",
    metadata: {
      gateway: "https://arweave.net",
      tags: ["manifest", "pipeline"],
    },
    orchestration: {
      engine: "temporal",
      workflowId: "publication-publication_arweave_1",
      workflowRunId: "temporal-run-arweave-1",
      workflowType: "programPublicationWorkflow",
      taskQueue: "agent-marketplace-publications",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:53:00.000Z",
    updatedAt: "2026-03-23T08:53:00.000Z",
  },
];

export const runs: Array<
  Run & {
    agentName: string;
  }
> = [
  {
    id: "run_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_pipeline",
    triggerType: "manual",
    status: "awaiting_approval",
    summary: "Prepared CRM task update and customer follow-up.",
    plannedActions: [
      "Read latest deal thread",
      "Prepare HubSpot follow-up task",
      "Draft customer-facing next steps",
    ],
    approvalRequirement: "required",
    approvalRequestId: "approval_1",
    orchestration: {
      engine: "temporal",
      workflowId: "run-run_1",
      workflowRunId: "temporal-run-1",
      workflowType: "agentRunWorkflow",
      taskQueue: "agent-marketplace-runs",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T09:20:00.000Z",
    updatedAt: "2026-03-23T09:22:00.000Z",
    agentName: "Pipeline Operator",
  },
  {
    id: "run_2",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_support",
    triggerType: "integration_event",
    status: "completed",
    summary: "Summarized inbound support thread and produced internal handoff.",
    plannedActions: [
      "Read inbox thread",
      "Summarize issue",
      "Post summary to Slack",
    ],
    approvalRequirement: "required",
    approvalRequestId: null,
    orchestration: {
      engine: "temporal",
      workflowId: "run-run_2",
      workflowRunId: "temporal-run-2",
      workflowType: "agentRunWorkflow",
      taskQueue: "agent-marketplace-runs",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T07:40:00.000Z",
    updatedAt: "2026-03-23T07:44:00.000Z",
    agentName: "Customer Support Agent",
  },
];

export const approvals: ApprovalRequest[] = [
  {
    id: "approval_1",
    runId: "run_1",
    workspaceId: "workspace_demo",
    status: "pending",
    summary: "Approve CRM write and outbound follow-up draft.",
    requestedActions: [
      "Execute crm.tasks.write",
      "Execute gmail.send",
    ],
    createdAt: "2026-03-23T09:22:00.000Z",
    resolvedAt: null,
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "audit_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "draft.published",
    entityType: "agent_team_draft",
    entityId: "draft_demo",
    payload: {
      agentCount: 2,
    },
    createdAt: "2026-03-23T09:12:00.000Z",
  },
  {
    id: "audit_2",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "integration.installed",
    entityType: "organization_integration",
    entityId: "int_slack",
    payload: {
      providerKey: "slack",
    },
    createdAt: "2026-03-23T08:55:00.000Z",
  },
  {
    id: "audit_3",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "program_file.published.base",
    entityType: "publication_record",
    entityId: "publication_base_1",
    payload: {
      programFileId: "program_file_1",
      target: "base",
    },
    createdAt: "2026-03-23T08:51:00.000Z",
  },
];
