import type {
  AgentSpec,
  AgentTeamDraft,
  ApprovalRequest,
  AuditEvent,
  OrganizationIntegration,
  ProgramFile,
  PublicationRecord,
  Run,
  ToolGrant,
} from "@agent-marketplace/contracts";

export const overviewStats = [
  { label: "Live agents", value: 2, hint: "2 published" },
  { label: "Pending approvals", value: 1, hint: "External writes waiting" },
  { label: "Integrations", value: 6, hint: "Org-wide installs" },
  { label: "Runs today", value: 2, hint: "1 completed, 1 pending" },
];

export const draftPreview: AgentTeamDraft = {
  id: "draft_demo",
  organizationId: "org_demo",
  workspaceId: "workspace_demo",
  title: "Revenue Recovery",
  brief:
    "We need a team that monitors inbound sales email, drafts next-step responses, updates CRM opportunities, and flags deals needing human approval before money-moving or customer-visible changes.",
  status: "generated",
  clarifications: [
    "Confirm which CRM is authoritative for pipeline stages.",
  ],
  generatedAgents: [
    {
      id: "draft_agent_pipeline",
      roleName: "Pipeline Operator",
      mission: "Keep the revenue pipeline current and escalate risky changes.",
      responsibilities: [
        "Review inbound deal updates.",
        "Prepare CRM and outbound response actions.",
      ],
      allowedTools: ["crm.contacts.read", "crm.tasks.write", "gmail.send"],
      knowledgeSources: ["workspace brief", "HubSpot install", "run history"],
      triggerModes: ["manual", "integration_event"],
      approvalPolicy: "required",
      successMetrics: ["Time to first follow-up", "CRM hygiene"],
      constraints: ["Require approval before outbound updates."],
    },
    {
      id: "draft_agent_support",
      roleName: "Customer Support Agent",
      mission: "Summarize support threads and prepare customer-ready drafts.",
      responsibilities: ["Read email threads.", "Draft responses and hand off."],
      allowedTools: ["gmail.read", "gmail.send", "slack.post"],
      knowledgeSources: ["workspace brief", "Gmail install", "Slack install"],
      triggerModes: ["manual", "integration_event"],
      approvalPolicy: "required",
      successMetrics: ["Queue response time", "Draft acceptance rate"],
      constraints: ["Do not send without approval."],
    },
  ],
  createdByUserId: "user_demo",
  updatedByUserId: "user_demo",
  createdAt: "2026-03-23T09:00:00.000Z",
  updatedAt: "2026-03-23T09:10:00.000Z",
};

export const marketingTeamExamples: AgentTeamDraft[] = [
  draftPreview,
  {
    id: "draft_demo_finance",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    title: "Payables & Receivables",
    brief:
      "We need a team that monitors vendor invoices, chases missing approvals, tracks receivables aging, drafts payment-status outreach, and escalates exceptions before cash flow problems compound.",
    status: "generated",
    clarifications: [
      "Confirm which accounting system is authoritative for invoice status and payment aging.",
    ],
    generatedAgents: [
      {
        id: "draft_agent_ap",
        roleName: "Accounts Payable Coordinator",
        mission: "Keep vendor obligations moving without missing approvals or payment windows.",
        responsibilities: [
          "Review inbound invoices and approval gaps.",
          "Prepare payment follow-ups and exception summaries.",
        ],
        allowedTools: ["gmail.read", "gmail.send", "slack.post"],
        knowledgeSources: ["workspace brief", "ERP export", "approval history"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Invoices cleared on time", "Approval lag reduced"],
        constraints: ["Do not release payment instructions without approval."],
      },
      {
        id: "draft_agent_ar",
        roleName: "Receivables Operator",
        mission: "Reduce aging receivables and surface collections risk early.",
        responsibilities: [
          "Track overdue balances and customer responses.",
          "Prepare outreach drafts and escalation notes.",
        ],
        allowedTools: ["crm.contacts.read", "gmail.send", "slack.post"],
        knowledgeSources: ["aging report", "workspace brief", "customer ledger"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Aging reduced", "Collections touched on time"],
        constraints: ["Escalate disputed balances before any external commitment."],
      },
    ],
    createdByUserId: "user_demo",
    updatedByUserId: "user_demo",
    createdAt: "2026-03-23T09:12:00.000Z",
    updatedAt: "2026-03-23T09:14:00.000Z",
  },
  {
    id: "draft_demo_leasing",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    title: "Leasing & Renewals",
    brief:
      "We need a team that captures inbound leasing inquiries, qualifies prospects, prepares follow-up sequences, tracks upcoming expirations, and drafts renewal outreach before occupancy risk shows up in the numbers.",
    status: "generated",
    clarifications: [
      "Confirm which PMS or CRM is authoritative for lease expiration dates and unit availability.",
    ],
    generatedAgents: [
      {
        id: "draft_agent_leasing",
        roleName: "Leasing Coordinator",
        mission: "Keep leasing inquiries moving from first contact to scheduled tour.",
        responsibilities: [
          "Review inbound prospects and lead sources.",
          "Draft follow-ups and surface high-intent prospects quickly.",
        ],
        allowedTools: ["gmail.read", "gmail.send", "slack.post"],
        knowledgeSources: ["workspace brief", "lead inbox", "availability feed"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Time to first response", "Tours scheduled"],
        constraints: ["Do not promise pricing or concessions without approval."],
      },
      {
        id: "draft_agent_renewals",
        roleName: "Renewal Operator",
        mission: "Reduce renewal leakage by tracking expiring leases and preparing timely outreach.",
        responsibilities: [
          "Watch upcoming expirations and tenant response status.",
          "Draft renewal reminders and escalation notes for at-risk residents.",
        ],
        allowedTools: ["crm.contacts.read", "gmail.send", "slack.post"],
        knowledgeSources: ["lease schedule", "workspace brief", "renewal history"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Renewal outreach on time", "At-risk leases escalated early"],
        constraints: ["Escalate pricing changes before any customer-visible commitment."],
      },
    ],
    createdByUserId: "user_demo",
    updatedByUserId: "user_demo",
    createdAt: "2026-03-23T09:16:00.000Z",
    updatedAt: "2026-03-23T09:18:00.000Z",
  },
  {
    id: "draft_demo_maintenance",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    title: "Maintenance Triage",
    brief:
      "We need a team that reviews maintenance requests, identifies emergencies, drafts resident updates, and escalates vendor dispatch issues before service levels slip.",
    status: "generated",
    clarifications: [
      "Confirm which work-order system is authoritative for dispatch status and vendor assignment.",
    ],
    generatedAgents: [
      {
        id: "draft_agent_triage",
        roleName: "Maintenance Intake Operator",
        mission: "Classify incoming maintenance issues quickly and route urgent problems immediately.",
        responsibilities: [
          "Review inbound requests and categorize severity.",
          "Prepare dispatch notes and resident-facing updates.",
        ],
        allowedTools: ["gmail.read", "gmail.send", "slack.post"],
        knowledgeSources: ["workspace brief", "ticket queue", "property rules"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Emergency response time", "Accurate first-pass classification"],
        constraints: ["Escalate emergencies immediately and do not close requests without confirmation."],
      },
      {
        id: "draft_agent_dispatch",
        roleName: "Vendor Dispatch Coordinator",
        mission: "Keep routine maintenance moving and surface vendor delays before residents feel them.",
        responsibilities: [
          "Track open work orders and vendor response gaps.",
          "Prepare follow-ups for overdue dispatches and unresolved visits.",
        ],
        allowedTools: ["crm.tasks.write", "gmail.send", "slack.post"],
        knowledgeSources: ["dispatch board", "vendor roster", "workspace brief"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Open work orders reduced", "Vendor delays escalated early"],
        constraints: ["Do not mark work complete without confirmed resolution."],
      },
    ],
    createdByUserId: "user_demo",
    updatedByUserId: "user_demo",
    createdAt: "2026-03-23T09:20:00.000Z",
    updatedAt: "2026-03-23T09:22:00.000Z",
  },
  {
    id: "draft_demo_collections",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    title: "Collections",
    brief:
      "We need a team that tracks delinquent balances, prioritizes accounts by risk and amount, drafts collection outreach, and escalates payment-plan or legal-review cases before receivables age out.",
    status: "generated",
    clarifications: [
      "Confirm which ledger or property system is authoritative for delinquency status and promise-to-pay tracking.",
    ],
    generatedAgents: [
      {
        id: "draft_agent_collections",
        roleName: "Collections Operator",
        mission: "Keep delinquent accounts moving through structured outreach without losing track of risk.",
        responsibilities: [
          "Review aged balances and recent tenant responses.",
          "Prepare outreach sequences and exception summaries.",
        ],
        allowedTools: ["gmail.read", "gmail.send", "slack.post"],
        knowledgeSources: ["aging report", "workspace brief", "payment history"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Delinquent balances reduced", "High-risk accounts contacted on time"],
        constraints: ["Escalate disputed balances and legal-risk cases before any firm commitment."],
      },
      {
        id: "draft_agent_promises",
        roleName: "Promise-to-Pay Tracker",
        mission: "Monitor promised payments and escalate broken commitments before they roll into larger loss.",
        responsibilities: [
          "Track promise-to-pay dates and missed follow-through.",
          "Prepare internal escalations and next-step reminders.",
        ],
        allowedTools: ["crm.tasks.write", "gmail.send", "slack.post"],
        knowledgeSources: ["collections notes", "workspace brief", "tenant ledger"],
        triggerModes: ["manual", "integration_event"],
        approvalPolicy: "required",
        successMetrics: ["Promises tracked on time", "Broken commitments escalated early"],
        constraints: ["Do not approve concessions or settlements without human approval."],
      },
    ],
    createdByUserId: "user_demo",
    updatedByUserId: "user_demo",
    createdAt: "2026-03-23T09:24:00.000Z",
    updatedAt: "2026-03-23T09:26:00.000Z",
  },
];

export const agents: AgentSpec[] = [
  {
    id: "agent_pipeline",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    displayName: "Pipeline Operator",
    mission: "Keep CRM and outbound comms aligned to real pipeline state.",
    responsibilities: ["Watch inbound updates", "Prepare CRM mutations", "Stage follow-up drafts"],
    allowedTools: ["crm.contacts.read", "crm.tasks.write", "gmail.send"],
    knowledgeSources: ["HubSpot", "workspace brief", "past approvals"],
    triggerModes: ["manual", "integration_event"],
    approvalPolicy: "required",
    successMetrics: ["Pipeline freshness", "Follow-up time"],
    constraints: ["External writes need approval"],
    status: "active",
    currentVersionId: "agent_version_pipeline",
    createdAt: "2026-03-23T08:00:00.000Z",
    updatedAt: "2026-03-23T08:15:00.000Z",
  },
  {
    id: "agent_support",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    displayName: "Customer Support Agent",
    mission: "Reduce inbox drag by preparing accurate support drafts.",
    responsibilities: ["Read threads", "Summarize context", "Prepare responses"],
    allowedTools: ["gmail.read", "gmail.send", "slack.post"],
    knowledgeSources: ["Gmail", "Slack", "workspace brief"],
    triggerModes: ["manual", "integration_event"],
    approvalPolicy: "required",
    successMetrics: ["Draft reuse rate", "Escalation quality"],
    constraints: ["Never send without approval"],
    status: "active",
    currentVersionId: "agent_version_support",
    createdAt: "2026-03-22T18:00:00.000Z",
    updatedAt: "2026-03-23T07:00:00.000Z",
  },
];

export const integrations: OrganizationIntegration[] = [
  {
    id: "int_openai",
    organizationId: "org_demo",
    providerKey: "openai",
    displayName: "OpenAI planner",
    status: "connected",
    authType: "api_key",
    scopes: ["llm.plan", "llm.draft", "llm.extract", "llm.review"],
    metadata: {
      defaultModel: "gpt-4.1-mini",
      defaultForPlanning: true,
      apiKeyLastFour: "4a9f",
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:58:00.000Z",
    updatedAt: "2026-03-23T09:04:00.000Z",
    lastValidatedAt: "2026-03-23T09:04:00.000Z",
  },
  {
    id: "int_google",
    organizationId: "org_demo",
    providerKey: "google-workspace",
    displayName: "Google Workspace",
    status: "connected",
    authType: "oauth",
    scopes: ["gmail.read", "gmail.send", "calendar.read"],
    metadata: { domain: "example.com" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-20T10:00:00.000Z",
    updatedAt: "2026-03-22T10:00:00.000Z",
    lastValidatedAt: "2026-03-23T08:45:00.000Z",
  },
  {
    id: "int_hubspot",
    organizationId: "org_demo",
    providerKey: "hubspot",
    displayName: "HubSpot",
    status: "connected",
    authType: "oauth",
    scopes: ["crm.contacts.read", "crm.tasks.write"],
    metadata: { portalId: "1234567" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-18T10:00:00.000Z",
    updatedAt: "2026-03-23T07:45:00.000Z",
    lastValidatedAt: "2026-03-23T08:30:00.000Z",
  },
  {
    id: "int_slack",
    organizationId: "org_demo",
    providerKey: "slack",
    displayName: "Ops Slack Workspace",
    status: "connected",
    authType: "oauth",
    scopes: ["slack.read", "slack.post", "slack.thread"],
    metadata: { workspace: "ops", defaultChannel: "#agent-ops" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:55:00.000Z",
    updatedAt: "2026-03-23T09:05:00.000Z",
    lastValidatedAt: "2026-03-23T09:05:00.000Z",
  },
  {
    id: "int_base",
    organizationId: "org_demo",
    providerKey: "base",
    displayName: "Base Publisher",
    status: "connected",
    authType: "wallet",
    scopes: ["base.publish_program", "base.register_manifest"],
    metadata: { chainId: 8453 },
    createdByUserId: "user_demo",
    createdAt: "2026-03-21T08:10:00.000Z",
    updatedAt: "2026-03-23T08:00:00.000Z",
    lastValidatedAt: "2026-03-23T08:00:00.000Z",
  },
  {
    id: "int_arweave",
    organizationId: "org_demo",
    providerKey: "arweave",
    displayName: "Arweave Publisher",
    status: "connected",
    authType: "wallet",
    scopes: ["arweave.upload_program", "arweave.pin_manifest"],
    metadata: { gateway: "https://arweave.net" },
    createdByUserId: "user_demo",
    createdAt: "2026-03-21T08:20:00.000Z",
    updatedAt: "2026-03-23T08:05:00.000Z",
    lastValidatedAt: "2026-03-23T08:05:00.000Z",
  },
];

export const programFiles: ProgramFile[] = [
  {
    id: "program_file_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_pipeline",
    name: "pipeline-operator.manifest.json",
    description: "Publishable manifest for the Pipeline Operator runtime and grants.",
    sourceType: "json",
    content: '{\n  "name": "Pipeline Operator",\n  "version": 1,\n  "tools": ["crm.contacts.read", "crm.tasks.write", "gmail.send"]\n}',
    tags: ["manifest", "pipeline", "base", "arweave"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:40:00.000Z",
    updatedAt: "2026-03-23T08:40:00.000Z",
  },
  {
    id: "program_file_2",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_support",
    name: "support-agent.ts",
    description: "Typed program entrypoint for the support agent workflow.",
    sourceType: "typescript",
    content: 'export const supportProgram = { role: "Customer Support Agent", approvalPolicy: "required" };\n',
    tags: ["runtime", "support", "typescript"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:42:00.000Z",
    updatedAt: "2026-03-23T08:42:00.000Z",
  },
];

export const publicationRecords: PublicationRecord[] = [
  {
    id: "publication_base_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    programFileId: "program_file_1",
    target: "base",
    status: "published",
    organizationIntegrationId: "int_base",
    summary: "Published the pipeline manifest to Base.",
    transactionId: "base_pipeline_manifest_v1",
    gatewayUrl: "https://basescan.org/address/pipeline-operator-manifest-json",
    metadata: {
      chainId: 8453,
      tags: ["manifest", "pipeline"],
    },
    orchestration: {
      engine: "temporal",
      workflowId: "publication-publication_base_1",
      workflowRunId: "temporal-run-base-1",
      workflowType: "programPublicationWorkflow",
      taskQueue: "agent-marketplace-publications",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:50:00.000Z",
    updatedAt: "2026-03-23T08:51:00.000Z",
  },
  {
    id: "publication_arweave_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    programFileId: "program_file_1",
    target: "arweave",
    status: "published",
    organizationIntegrationId: "int_arweave",
    summary: "Pinned the same manifest to Arweave for immutable retrieval.",
    transactionId: "ar_pipeline_manifest_v1",
    gatewayUrl: "https://arweave.net/pipeline-operator-manifest-json",
    metadata: {
      gateway: "https://arweave.net",
      tags: ["manifest", "pipeline"],
    },
    orchestration: {
      engine: "temporal",
      workflowId: "publication-publication_arweave_1",
      workflowRunId: "temporal-run-arweave-1",
      workflowType: "programPublicationWorkflow",
      taskQueue: "agent-marketplace-publications",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T08:53:00.000Z",
    updatedAt: "2026-03-23T08:53:00.000Z",
  },
];

export const toolGrants: ToolGrant[] = [
  {
    id: "tool_grant_pipeline_hubspot",
    workspaceId: "workspace_demo",
    agentId: "agent_pipeline",
    organizationIntegrationId: "int_hubspot",
    providerKey: "hubspot",
    tools: ["crm.contacts.read", "crm.tasks.write"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T09:06:00.000Z",
  },
  {
    id: "tool_grant_pipeline_google",
    workspaceId: "workspace_demo",
    agentId: "agent_pipeline",
    organizationIntegrationId: "int_google",
    providerKey: "google-workspace",
    tools: ["gmail.send"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T09:06:30.000Z",
  },
  {
    id: "tool_grant_support_google",
    workspaceId: "workspace_demo",
    agentId: "agent_support",
    organizationIntegrationId: "int_google",
    providerKey: "google-workspace",
    tools: ["gmail.read", "gmail.send"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T09:07:00.000Z",
  },
  {
    id: "tool_grant_support_slack",
    workspaceId: "workspace_demo",
    agentId: "agent_support",
    organizationIntegrationId: "int_slack",
    providerKey: "slack",
    tools: ["slack.post"],
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T09:07:30.000Z",
  },
];

export const getToolGrantsForAgent = (agentId: string) =>
  toolGrants.filter((grant) => grant.agentId === agentId);

export const getGrantedToolsForAgent = (agent: AgentSpec) => {
  const grantedTools = new Set(getToolGrantsForAgent(agent.id).flatMap((grant) => grant.tools));
  return agent.allowedTools.filter((tool) => grantedTools.has(tool));
};

export const getMissingToolsForAgent = (agent: AgentSpec) => {
  const grantedTools = new Set(getToolGrantsForAgent(agent.id).flatMap((grant) => grant.tools));
  return agent.allowedTools.filter((tool) => !grantedTools.has(tool));
};

export const runs: Array<
  Run & {
    agentName: string;
  }
> = [
  {
    id: "run_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_pipeline",
    triggerType: "manual",
    status: "awaiting_approval",
    summary: "Prepared CRM task update and customer follow-up.",
    plannedActions: [
      "Read latest deal thread",
      "Prepare HubSpot follow-up task",
      "Draft customer-facing next steps",
    ],
    approvalRequirement: "required",
    approvalRequestId: "approval_1",
    orchestration: {
      engine: "temporal",
      workflowId: "run-run_1",
      workflowRunId: "temporal-run-1",
      workflowType: "agentRunWorkflow",
      taskQueue: "agent-marketplace-runs",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T09:20:00.000Z",
    updatedAt: "2026-03-23T09:22:00.000Z",
    agentName: "Pipeline Operator",
  },
  {
    id: "run_2",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    agentId: "agent_support",
    triggerType: "integration_event",
    status: "completed",
    summary: "Summarized inbound support thread and produced internal handoff.",
    plannedActions: [
      "Read inbox thread",
      "Summarize issue",
      "Post summary to Slack",
    ],
    approvalRequirement: "required",
    approvalRequestId: null,
    orchestration: {
      engine: "temporal",
      workflowId: "run-run_2",
      workflowRunId: "temporal-run-2",
      workflowType: "agentRunWorkflow",
      taskQueue: "agent-marketplace-runs",
      namespace: "default",
      status: "started",
      lastError: null,
    },
    createdByUserId: "user_demo",
    createdAt: "2026-03-23T07:40:00.000Z",
    updatedAt: "2026-03-23T07:44:00.000Z",
    agentName: "Customer Support Agent",
  },
];

export const approvals: ApprovalRequest[] = [
  {
    id: "approval_1",
    runId: "run_1",
    workspaceId: "workspace_demo",
    status: "pending",
    summary: "Approve CRM write and outbound follow-up draft.",
    requestedActions: [
      "Execute crm.tasks.write",
      "Execute gmail.send",
    ],
    createdAt: "2026-03-23T09:22:00.000Z",
    resolvedAt: null,
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "audit_1",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "draft.published",
    entityType: "agent_team_draft",
    entityId: "draft_demo",
    payload: {
      agentCount: 2,
    },
    createdAt: "2026-03-23T09:12:00.000Z",
  },
  {
    id: "audit_2",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "integration.tested",
    entityType: "organization_integration",
    entityId: "int_openai",
    payload: {
      providerKey: "openai",
      model: "gpt-4.1-mini",
    },
    createdAt: "2026-03-23T09:04:00.000Z",
  },
  {
    id: "audit_3",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "integration.oauth_completed",
    entityType: "organization_integration",
    entityId: "int_slack",
    payload: {
      providerKey: "slack",
    },
    createdAt: "2026-03-23T09:05:00.000Z",
  },
  {
    id: "audit_4",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "agent.tool_grant.updated",
    entityType: "tool_grant",
    entityId: "tool_grant_support_slack",
    payload: {
      agentId: "agent_support",
      providerKey: "slack",
      tools: ["slack.post"],
    },
    createdAt: "2026-03-23T09:07:30.000Z",
  },
  {
    id: "audit_5",
    organizationId: "org_demo",
    workspaceId: "workspace_demo",
    userId: "user_demo",
    eventType: "program_file.published.base",
    entityType: "publication_record",
    entityId: "publication_base_1",
    payload: {
      programFileId: "program_file_1",
      target: "base",
    },
    createdAt: "2026-03-23T08:51:00.000Z",
  },
];
